spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    name:
    username: FaaS
    password:
    type: org.h2.jdbcx.JdbcDataSource
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show_sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true

zuul:
  routes:
    serviceA:
      path: /serviceA
      url: forward:/
    serviceB:
      path: /serviceB
      url: forward:/
    serviceC:
      path: /serviceC
      url: forward:/
    serviceD:
      strip-prefix: false
      path: /serviceD/**
      url: forward:/
    serviceE:
      path: /serviceE
      url: forward:/
    serviceF:
      path: /serviceF
      url: forward:/
    serviceG:
      path: /serviceG
      url: forward:/
    serviceH:
      path: /serviceH
      url: forward:/
    serviceI:
      path: /serviceI
      url: forward:/
  ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      serviceA:
        - limit: 10
          refresh-interval: 60
          type:
            - origin
      serviceB:
        - limit: 2
          refresh-interval: 2
          type:
            - origin
      serviceD:
        - limit: 2
          refresh-interval: 60
          type:
            - url
      serviceE:
        - quota: 1s
          refresh-interval: 60s
          type:
            - origin
      serviceF:
        - limit: 2
          refresh-interval: 60
          type:
            - origin=127.0.0.1
          breakOnMatch: true
        - limit: 1
          refresh-interval: 60
          type:
            - origin
          breakOnMatch: true
      serviceG:
        - limit: 2
          refresh-interval: 60
          type:
            - origin=128.0.0.1
          breakOnMatch: true
        - limit: 1
          refresh-interval: 60
          type:
            - origin
          breakOnMatch: true
      serviceH:
        - limit: 2
          refresh-interval: 60
          type:
            - origin=127.0.0.0/22
          breakOnMatch: true
        - limit: 1
          refresh-interval: 60
          type:
            - origin
          breakOnMatch: true
      serviceI:
        - limit: 2
          refresh-interval: 60
          type:
            - origin=126.0.0.0/22
          breakOnMatch: true
        - limit: 1
          refresh-interval: 60
          type:
            - origin
          breakOnMatch: true
  strip-prefix: true

logging:
  level:
    ROOT: error